### PR TITLE
Fixes #67

### LINKED ISSUE #67: [New Feature]: Adding Auto-commenting feature for PR raised
### 🎮 feature Request

- When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. 
- However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.
- This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. 
- This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

### Point down the features

- This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs.
- By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. 
- This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
## PR Description 📜

This adds an autocommenting feature on the PRs raised.
Fixes #67 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by thevirengarg** [comment]
@Sambit-Mondal Make sure the Default program is GSSoC'24. And the label of GSSoC'24 is 'gssoc'

**Comment by Sambit-Mondal** [comment]
@thevirengarg I'll surely do the changes. I'll be travelling for the next 7-8 hours. Once I reach, I'll do the changes. 
Thank you for understanding!

**Comment by thevirengarg** [comment]
@Sambit-Mondal Yeah, No problem. You can take your time, you have a buffer of 3-4 days.

**Comment by Sambit-Mondal** [comment]
@thevirengarg Sir, I've done the changes as per requirements. Kindly check.
Thank you!

**Comment by thevirengarg** [comment]
@Sambit-Mondal Project admin has already added auto-commenting feature. You can contact him, he'll approve your PR. @Durgesh4993

**Comment by Durgesh4993** [comment]
@Sambit-Mondal You have already raised this type of PR in any other repository, you should raise any other issue because in last they will came into spam, that is reason why i did't merge you remaining same PRs

**Comment by Durgesh4993** [comment]
And last time after change i have told you you should connect with me but you forget to connect. I want to talk on this topic

**Comment by Sambit-Mondal** [comment]
Okay

**Pull request closed without merging**
