### PR TITLE
REORGANISED all the files into different folders

### LINKED ISSUE #211: Reorganise the repository and make different files for js, css and img files so that it becomes more accessible and visually good
### 🎮 feature Request

Make different folders for img/png, css, and js files and change all their references accordingly

### Point down the features

feature points:

Becomes easy to access

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by partha120804**
## PR Description 📜

All files are reorganised into subfolders of different types, js, css, images
Fixes #211 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by partha120804** [comment]
@thevirengarg 
Hello Sir, please review this PR.

**Review by thevirengarg — CHANGES_REQUESTED** [review]
Good work, just resolve the conflict.

**Comment by partha120804** [comment]
the resolve conflicts page is not working for some reason.

**Comment by partha120804** [comment]
@thevirengarg please merge this PR before other PRs so that no other conflicts rise 😄

**Review by thevirengarg — APPROVED** [review]

**Pull request merged**
