### PR TITLE
feat: 404 not found page added

### LINKED ISSUE #146: [New Feature]: Add a 404 not found page with the game theme
### 🎮 feature Request

Add a 404 not found page with the game theme

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## PR Description 📜
 
404 not found page added with responsive 

Fixes #146 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by thevirengarg — APPROVED** [review]

**Comment by RamakrushnaBiswal** [comment]
@thevirengarg its not good why my PR is not merged

**Comment by thevirengarg** [comment]
@RamakrushnaBiswal Okay, Tell me what's the point of adding a random 404 page to the repo which you have copied from some other project.

**Comment by RamakrushnaBiswal** [comment]
I didn't copied anywhere 😞,I just pic the image from storyset.com then add it

**Comment by RamakrushnaBiswal** [comment]
@thevirengarg

**Pull request closed without merging**
