### PR TITLE
Added ScrollToTop Button with Floating animation 

### PR DESCRIPTION
**Pull request by Damini2004**
## PR Description 📜

Added button with Floating animation to look it more realistic.

Kinldy add suitable level as per the styling.

Fixes # #216 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>
## Add your screenshots(Optional) 📸

https://github.com/ChromeGaming/Physi-c-Tech/issues

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Damini2004** [comment]
@thevirengarg Kindly review the PR.

**Comment by thevirengarg** [comment]
@Damini2004 Please resolve the conflicts

**Comment by Damini2004** [comment]
@thevirengarg  resolved kinldy view it.

**Comment by thevirengarg** [comment]
@Damini2004 Resolve the conflicts

**Pull request merged**
