### PR TITLE
Fixes #65

### LINKED ISSUE #65: [New Feature]: Adding Auto-commenting feature on Issues
### 🎮 feature Request

- When issues are created in a project, it is important to provide immediate acknowledgment and guidance to the issue creator. However, manually commenting on every newly created issue can be time-consuming for maintainers, leading to delays and inconsistency in communication. 
- This can result in contributors feeling ignored or discouraged from further participation.
- I would like an automated feature that posts a predefined comment on an issue as soon as it is created. 
- This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information.
-  The automation should be customizable to accommodate different project workflows and communication styles.

### Point down the features

- This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. 
- By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. 
- This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
## PR Description 📜

Added an auto-commenting feature for the issues opened on this repository.
Fixes #65 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by thevirengarg** [comment]
@Sambit-Mondal Add a feature to auto label the issue and the pull request. Under the label gssoc

**Comment by Sambit-Mondal** [comment]
@thevirengarg In this same PR?

**Comment by thevirengarg** [comment]
> @thevirengarg In this same PR?

Yes, commit more in this PR or you can close this PR and raise a new one.

**Comment by Sambit-Mondal** [comment]
@thevirengarg I've added the auto-labelling feature for Issues.
For PRs, I had raised an "auto-commenting feature issue for PRs" 5 days ago (Reference: #67 )
Kindly assign that issue to me. I'll do the same for PRs.
Thank you!

**Comment by thevirengarg** [comment]
@Sambit-Mondal the label of the issue and the pr must be 'gssoc' not 'GSSoC' and the label must be added to the issue if the contributor selects the option for gssoc else there must be no label. 
while raising an issue or creating a PR there must be a dropdown "This issue should be considered under which program?" and in the options there must be no program and gssoc. The default must be gssoc. (use dropdown or a checkbox).

**Comment by Sambit-Mondal** [comment]
@thevirengarg Okay, got it! I'll surely make the changes.

**Comment by thevirengarg** [comment]
@Sambit-Mondal Ask them to join the discord community for better communication https://discord.gg/BjzSZq8GnN

**Comment by thevirengarg** [comment]
@Durgesh4993 Could you please review this pull request

**Pull request closed without merging**
