### PR TITLE
Added the double click to clone feature.

### LINKED ISSUE #235: [New Feature]: Double click to clone a selection
### 🎮 feature Request

feature logic and basic description

I want to add a feature when double clicking on a icon will clone it, so that you dont have to find the item in the menu if you need another similiar element.

### Point down the features

feature points

If you want to create OPPOSITE from MAGNET, instead of dragging magnet twice you can just drag it once to top and then double click it to get 2 magnets and then add them.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by partha120804**
## PR Description 📜

Now users can double click an item in forge to use it.
Fixes #235 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

## Screen record 

https://github.com/ChromeGaming/Physi-c-Tech/assets/138643473/caf82b0a-9646-4d1f-af10-56a034d70e59

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by partha120804** [comment]
@thevirengarg @Durgesh4993 please take a look and review this PR

**Comment by partha120804** [comment]
@thevirengarg ?

**Comment by partha120804** [comment]
@thevirengarg hey, please review this PR

**Comment by partha120804** [comment]
Ok

**Comment by partha120804** [comment]
@thevirengarg the conflicts has been resolved please check the PR now

**Comment by thevirengarg** [comment]
@partha120804 Conflicts are not yet resolved, check the PR.

**Comment by partha120804** [comment]
@thevirengarg done

**Pull request merged**
