### PR TITLE
Add Sound in game page

### LINKED ISSUE #133: Adding the sound on /off in game page instead of home
It would be easy for users if the sound option is in game page instead of home
/gssoc24

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
## PR Description 📜
Adding the sound on /off in game page instead of home
Fixes #133

<hr>

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ x] I have added screenshot for review.
image

### CODE REVIEW

**Comment by thevirengarg** [comment]
@Rohitha-pudu When I click on the sound on icon it should change to sound off icon.

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu When I click on the sound on icon it should change to sound off icon.

it is changing

**Comment by thevirengarg** [comment]
@Rohitha-pudu Resolve the conflicts

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu Resolve the conflicts

image

**Comment by thevirengarg** [comment]
@Rohitha-pudu Discard these commits, update your forked repository and commit again.

**Comment by Rohitha-pudu** [comment]
can u check @thevirengarg  i have kept PR from my main

**Comment by Rohitha-pudu** [comment]
opened Another PR #143

**Comment by thevirengarg** [comment]
@Rohitha-pudu Resolve conflicts

**Comment by Rohitha-pudu** [comment]
I kept another PR @thevirengarg #143

**Pull request closed without merging**
